In [10]:
import pandas as pd
import os

os.chdir(r"C:\Users\hp\bluestock_mf_capstone\data\raw")

print(os.getcwd())

C:\Users\hp\bluestock_mf_capstone\data\raw

In [11]:
fund_master = pd.read_csv("01_fund_master.csv")
nav_history = pd.read_csv("02_nav_history.csv")
scheme_perf = pd.read_csv("07_scheme_performance.csv")
transactions = pd.read_csv("08_investor_transactions.csv")

In [12]:
# Check Data types
for name, df in {
    "fund_master": fund_master,
    "nav_history": nav_history,
    "scheme_performance": scheme_perf,
    "transactions": transactions
}.items():
    
    print("\n" + "="*50)
    print(name.upper())
    print(df.info())

==================================================
FUND_MASTER
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None

==================================================
NAV_HISTORY
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
None

==================================================
SCHEME_PERFORMANCE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB
None

==================================================
TRANSACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB
None

In [13]:
# Check Missing Values
for name, df in {
    "fund_master": fund_master,
    "nav_history": nav_history,
    "scheme_performance": scheme_perf,
    "transactions": transactions
}.items():
    
    print("\n" + "="*50)
    print(name.upper())
    print(df.isnull().sum())

==================================================
FUND_MASTER
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

==================================================
NAV_HISTORY
amfi_code    0
date         0
nav          0
dtype: int64

==================================================
SCHEME_PERFORMANCE
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

==================================================
TRANSACTIONS
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [16]:
# Check Duplicate Records
for name, df in {
    "fund_master": fund_master,
    "nav_history": nav_history,
    "scheme_performance": scheme_perf,
    "transactions": transactions
}.items():
    
    print("\n" + "="*50)
    print(name.upper())
    print("Duplicates:", df.duplicated().sum())

==================================================
FUND_MASTER
Duplicates: 0

==================================================
NAV_HISTORY
Duplicates: 0

==================================================
SCHEME_PERFORMANCE
Duplicates: 0

==================================================
TRANSACTIONS
Duplicates: 0

In [17]:
# Summary Statistics
scheme_perf.describe()

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000
mean,120247.000000,14.376000,14.089000,14.516750,12.835500,1.253500,0.873250,1.361750,2.082500,14.962500,-19.200250,26091.60000,1.237000,4.250000
std,14534.998667,4.883023,4.617253,4.454021,4.740972,0.447412,0.224846,1.475805,2.203144,6.669282,8.819164,13809.11134,0.386584,0.742484
min,100016.000000,4.260000,5.140000,5.430000,3.960000,0.510000,0.220000,0.800000,1.030000,0.500000,-33.500000,979.00000,0.550000,3.000000
25%,118632.750000,11.735000,12.035000,12.340000,10.690000,0.887500,0.890000,0.865000,1.270000,14.000000,-25.062500,17400.50000,0.787500,4.000000
50%,119551.500000,14.620000,14.205000,14.185000,13.090000,1.205000,0.960000,0.925000,1.445000,14.000000,-20.600000,26713.00000,1.425000,4.000000
75%,120842.250000,16.392500,15.882500,17.585000,14.775000,1.700000,1.000000,0.985000,1.637500,19.000000,-14.255000,38125.00000,1.540000,5.000000
max,149324.000000,24.930000,23.390000,23.800000,22.160000,1.980000,1.040000,7.680000,10.370000,25.000000,-2.230000,49046.00000,1.640000,5.000000

In [18]:
transactions.describe()

           amfi_code     amount_inr  annual_income_lakh
count   32778.000000   32778.000000        32778.000000
mean   120264.617518  107437.318628           26.181219
std     14370.205345  150415.905084           20.805425
min    100016.000000     400.000000            3.000000
25%    118632.000000    3153.000000           10.600000
50%    119551.000000   17782.500000           19.700000
75%    120843.000000  189324.250000           37.400000
max    149324.000000  597498.000000           99.700000

In [19]:
# Check data types and convert date columns.nav_history.info()
transactions.info()
nav_history['date'] = pd.to_datetime(nav_history['date'])

transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date']
)

In [20]:
nav_history.info()
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB